# Generated by Django 5.1.2 on 2024-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_line1',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_line4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='enable_facebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='enable_instagram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='enable_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='enable_x',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='enable_youtube',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='footer_logo',
            field=models.ImageField(default='default_logo.png', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='header_logo',
            field=models.ImageField(default='default_logo.png', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sidebar_logo',
            field=models.ImageField(default='default_logo.png', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='x_link',
            field=models.URLField(blank=True, help_text='X was formerly known as Twitter', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
