# Generated by Django 5.1.2 on 2024-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_companyinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='enable_tagline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
