# Generated by Django 5.1.2 on 2024-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_companyinfo_email_icon_companyinfo_location_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='x_icon',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='x_video',
            field=models.FileField(blank=True, default='default_x_video.mp4', help_text='Please Upload Animation Video', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email_icon',
            field=models.ImageField(blank=True, default='default_email_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='facebook_icon',
            field=models.ImageField(blank=True, default='default_facebook_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram_icon',
            field=models.ImageField(blank=True, default='default_instagram_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='location_icon',
            field=models.ImageField(blank=True, default='default_location_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone_icon',
            field=models.ImageField(blank=True, default='default_phone_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp_icon',
            field=models.ImageField(blank=True, default='default_whatsapp_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='youtube_icon',
            field=models.ImageField(blank=True, default='default_youtube_icon.png', help_text='Please Upload Animation GIF', null=True, upload_to='icons/'),
        ),
    ]
