# Generated by Django 5.1.2 on 2024-10-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_happyclients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HappyClients',
            new_name='HappyClient',
        ),
    ]
