# Generated by Django 5.1.2 on 2024-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='photographer_name',
            field=models.CharField(default='Photographername', max_length=100),
        ),
    ]
