# Generated by Django 5.1.2 on 2024-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_companyinfo_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='gif_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='intro_gif',
            field=models.ImageField(blank=True, null=True, upload_to='company_intro_gifs/'),
        ),
    ]
