# Generated by Django 5.1.2 on 2024-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_babypropsgallery_babypropsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypropsgallery',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10),
        ),
    ]
