# Generated by Django 5.1.2 on 2024-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_babypropsimage_update_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypropsimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
