# Generated by Django 5.1.2 on 2024-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_babypropsimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypropsimage',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
