# Generated by Django 5.1.2 on 2024-10-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_companyinfo_babyprops_header_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=255)),
                ('enable', models.BooleanField(default=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('orientation', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='left', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OurServicesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='baby_props_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enable', models.BooleanField(default=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.ourservices')),
            ],
        ),
    ]
