# Generated by Django 5.1.2 on 2024-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_ourservices_ourservicesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
