# Generated by Django 5.1.2 on 2024-10-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_ourservices_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurServices',
            new_name='OurService',
        ),
    ]
