# Generated by Django 5.1.2 on 2024-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_ourservice_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservicesimage',
            name='image',
            field=models.ImageField(upload_to='service_images/'),
        ),
    ]
