# Generated by Django 5.1.2 on 2024-10-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailConfiguration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='toemail',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='toemail',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
