# Generated by Django 5.1.2 on 2024-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailConfiguration', '0003_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='toemail',
            name='send_ImgId',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toemail',
            name='send_otp',
            field=models.BooleanField(default=False),
        ),
    ]
