# Generated by Django 5.1.2 on 2024-10-26 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0007_image_remove_product_images_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_shoots',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='remove_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
