# Generated by Django 5.1.2 on 2024-10-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0009_show_remove_product_images_showphoto_delete_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showphoto',
            name='show',
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='show_photos/')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='UserPage.userdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='ShowPhoto',
        ),
    ]
