# Generated by Django 5.1.2 on 2024-10-29 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0011_userfavorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
        migrations.RenameModel(
            old_name='UserFavorites',
            new_name='UserFavorite',
        ),
        migrations.RenameModel(
            old_name='UserImages',
            new_name='UserImage',
        ),
    ]
