# Generated by Django 5.1.2 on 2024-12-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0012_rename_userdetails_userdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserPage.userimage'),
        ),
    ]
